# fly.toml app configuration file generated for ponder on 2023-06-19T15:05:30+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ponder"
primary_region = "lax"

[[services]]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.http_checks]]
    interval = 10_000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2_000
    tls_skip_verify = false
